# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230727-120816-denim-controller

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: SpacyNLP
    model: "en_core_web_lg-3.4.1"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 300
    constrain_similarities: True
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: True

policies: 
  - name: TEDPolicy
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: 'action_default_fallback'
    enable_fallback_prediction: True
  - name: MemoizationPolicy