
FROM rasa/rasa-sdk:3.6.2

# Use subdirectory as working directory
WORKDIR /app

# Copy any additional custom requirements, if necessary (uncomment next line)
COPY . .
# Change back to root user to install dependencies
USER root

RUN pip install thefuzz word2number
# Install extra requirements for actions code, if necessary (uncomment next line)
#RUN pip install torch==1.10.0+cpu torchvision==0.11.0+cpu torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html


# Copy actions folder to working directory
COPY ./actions /app/actions

# By best practices, don't run the code with root user
# USER 1001
